In [17]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from pathlib import Path
import spacy as sp

In [18]:
input_path=Path().resolve()/'input'

# Loading Dataa

In [19]:
testing_data=pl.read_csv(input_path/'Corona_NLP_test.csv')

In [20]:
training_data=pl.read_csv(input_path/'Corona_NLP_train.csv')

# Data Preprocessing

### Data Preprocessing pipeline:
1. clean missing values - Done
2. fix data types -Done
3. Text Cleaning -Done
4. tokenize the text of the target column -Done
5. remove stop words Done
6. Stemming words (Porter Stemmer) -Done

Note: Lemmatization is a very costly operation that takes minutes sometimes hours which is not suitable entirely for this project

In [21]:
testing_data.null_count()

shape: (1, 6)
┌──────────┬────────────┬──────────┬─────────┬───────────────┬───────────┐
│ UserName ┆ ScreenName ┆ Location ┆ TweetAt ┆ OriginalTweet ┆ Sentiment │
│ ---      ┆ ---        ┆ ---      ┆ ---     ┆ ---           ┆ ---       │
│ u32      ┆ u32        ┆ u32      ┆ u32     ┆ u32           ┆ u32       │
╞══════════╪════════════╪══════════╪═════════╪═══════════════╪═══════════╡
│ 0        ┆ 0          ┆ 834      ┆ 0       ┆ 0             ┆ 0         │
└──────────┴────────────┴──────────┴─────────┴───────────────┴───────────┘

In [22]:
# checking nulls
training_data.null_count()

shape: (1, 6)
┌──────────┬────────────┬──────────┬─────────┬───────────────┬───────────┐
│ UserName ┆ ScreenName ┆ Location ┆ TweetAt ┆ OriginalTweet ┆ Sentiment │
│ ---      ┆ ---        ┆ ---      ┆ ---     ┆ ---           ┆ ---       │
│ u32      ┆ u32        ┆ u32      ┆ u32     ┆ u32           ┆ u32       │
╞══════════╪════════════╪══════════╪═════════╪═══════════════╪═══════════╡
│ 0        ┆ 0          ┆ 8590     ┆ 0       ┆ 0             ┆ 0         │
└──────────┴────────────┴──────────┴─────────┴───────────────┴───────────┘

null exists at location

We will impute those nulls with unknown value

In [23]:
training_data=training_data.with_columns(pl.col('Location').fill_null('unknown'))
training_data.null_count()

shape: (1, 6)
┌──────────┬────────────┬──────────┬─────────┬───────────────┬───────────┐
│ UserName ┆ ScreenName ┆ Location ┆ TweetAt ┆ OriginalTweet ┆ Sentiment │
│ ---      ┆ ---        ┆ ---      ┆ ---     ┆ ---           ┆ ---       │
│ u32      ┆ u32        ┆ u32      ┆ u32     ┆ u32           ┆ u32       │
╞══════════╪════════════╪══════════╪═════════╪═══════════════╪═══════════╡
│ 0        ┆ 0          ┆ 0        ┆ 0       ┆ 0             ┆ 0         │
└──────────┴────────────┴──────────┴─────────┴───────────────┴───────────┘

In [24]:
testing_data=testing_data.with_columns(pl.col('Location').fill_null('unknown'))
testing_data.null_count()

shape: (1, 6)
┌──────────┬────────────┬──────────┬─────────┬───────────────┬───────────┐
│ UserName ┆ ScreenName ┆ Location ┆ TweetAt ┆ OriginalTweet ┆ Sentiment │
│ ---      ┆ ---        ┆ ---      ┆ ---     ┆ ---           ┆ ---       │
│ u32      ┆ u32        ┆ u32      ┆ u32     ┆ u32           ┆ u32       │
╞══════════╪════════════╪══════════╪═════════╪═══════════════╪═══════════╡
│ 0        ┆ 0          ┆ 0        ┆ 0       ┆ 0             ┆ 0         │
└──────────┴────────────┴──────────┴─────────┴───────────────┴───────────┘

In [25]:
# Converting the tweetat to polars datetime
training_data=training_data.with_columns(pl.col('TweetAt').str.to_date())
testing_data=testing_data.with_columns(pl.col('TweetAt').str.to_date())

#### clean data and tokenize

In [26]:
from lib import TextClassification
preprocessor=TextClassification(training_data)

In [27]:
# Method one using spacy cleaner --> very slow
# data=training_data.with_columns(pl.col('OriginalTweet').map_elements(lambda x: preprocess_spacy(x), return_dtype=pl.String))
# data.select(pl.col('OriginalTweet')).to_series().to_list()

In [28]:
# Very Fast method --polars nativen method
training_data=training_data.pipe(preprocessor.preprocess_pl_native)
testing_data=testing_data.pipe(preprocessor.preprocess_pl_native)

#### Removing stop words and punc

In [29]:
training_data=training_data.with_columns(
    pl.col('OriginalTweet').str.split(' ').map_elements(
        lambda x: preprocessor.remove_stop_words_and_punc(x), return_dtype=pl.String))
testing_data=testing_data.with_columns(
    pl.col('OriginalTweet').str.split(' ').map_elements(
        lambda x: preprocessor.remove_stop_words_and_punc(x), return_dtype=pl.String))

### Stemming

In [30]:
# Stemming words using porter stemming
training_data=training_data.with_columns(
    pl.col('OriginalTweet').map_elements(
        lambda x: preprocessor.porter_stem(x), return_dtype=pl.String))

testing_data=testing_data.with_columns(
    pl.col('OriginalTweet').map_elements(
        lambda x: preprocessor.porter_stem(x), return_dtype=pl.String))

# Data Exploration

### Data Exploration Steps:
1. get insights from the data
2. printing statistics
3. Checking missing values and duplicates
4. checking categorical distribution
5. Printing some plots (Barplot, Pie chart)
6. Word Cloud Plot
7. Word Cloud For each sentiment
8. Word counter for each sentiment
9. Text Length for each Sentiment

In [ ]:
training_data.head(10)

In [ ]:
training_data.describe()

### Checking duplicates

In [ ]:
is_dup=training_data.is_duplicated()
training_data.filter(is_dup)

There are no duplicates within the data

There are many null values in the location field <br>
Date format for the TweetAt is not accurate needs to be changed

In [ ]:
## understanding screen name
training_data.select(pl.col('ScreenName')).unique().count()

In [ ]:
# All values are unique so its an identity to the test

In [ ]:
# describing the categorical variables
training_data.to_pandas().describe(include="object")

- Most common location is Londan 
- Most common tweet date is 3448
- Most common Sentiment is Positive

In [ ]:
# Visualizing the sentiment column`

In [ ]:
from lib import TextClassification
sentiment_data=training_data.group_by('Sentiment').len().select(pl.col('Sentiment'), pl.col('len').alias('Counts'))

In [ ]:
Plots=TextClassification(sentiment_data)
Plots.barplot_seaborn('Sentiment','Counts')

In [ ]:
Plots.pie('Counts','Sentiment')

In [ ]:
# Correlation between Sentiment and Original Tweet
data_corr=training_data.select(pl.corr('OriginalTweet','Sentiment',method="spearman"))
data_corr

### Word cloud plot

In [ ]:
Plots=TextClassification(training_data)
Plots.WorldCloud()

### Word cloud for Neutral Sentiment

In [ ]:
Plots.WorldCloud('Neutral')

### Word cloud for Extermely Negative Sentiment

In [ ]:
Plots.WorldCloud('Extremely Negative')

### Word cloud for Negative Sentiment

In [ ]:
Plots.WorldCloud('Negative')

### Word cloud for Positive Sentiment

In [ ]:
Plots.WorldCloud('Positive')

### Word cloud for Exteremly Positive Sentiment

In [ ]:
Plots.WorldCloud('Extremely Positive')

_______________________

### Top Words Count for Neutral Sentiment

In [ ]:
Plots.Top_words('Neutral')

### Top Words Count for Extermely Negative Sentiment

In [ ]:
Plots.Top_words('Extremely Negative')

### Top Words Count for Negative Sentiment

In [ ]:
Plots.Top_words('Negative')

### Top Words Count for Positive Sentiment

In [ ]:
Plots.Top_words('Positive')

### Top Words Count for Exteremly Positive Sentiment

In [ ]:
Plots.Top_words('Extremely Positive')

### Boxplots for the Text Length for each Sentiment

In [ ]:
Plots.boxplot()

# Modelling

### Modelling Pipeline:
1. Apply TFIDF vectorizer to the training and testing data
2. Run the three selected models (Logistic Regression, Naive Bayes, Random Forest)
3. Create a function to evaluate those models with visualization
4. compare the performance of those models.
5. Perform Hyperparameter tuning -> a function applied to all three models
6. Compare model's performance before and after tuning with visualization
7. Selection of the best Model based on the evaluation metrics.

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf=TfidfVectorizer()
tf_idf?

Type:        TfidfVectorizer
String form: TfidfVectorizer()
File:        ~/.virtualenvs/crosscompute/lib/python3.11/site-packages/sklearn/feature_extraction/text.py
Docstring:
Convert a collection of raw documents to a matrix of TF-IDF features.

Equivalent to :class:`CountVectorizer` followed by
:class:`TfidfTransformer`.

For an example of usage, see
:ref:`sphx_glr_auto_examples_text_plot_document_classification_20newsgroups.py`.

For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.

For an example of document clustering and comparison with
:class:`~sklearn.feature_extraction.text.HashingVectorizer`, see
:ref:`sphx_glr_auto_examples_text_plot_document_clustering.py`.

Read more in the :ref:`User Guide <text_feature_extraction>`.

Parameters
----------
input : {'filename', 'file', 'content'}, default='content'
    - If `'filename'`, the sequence passed as an argument to fit is
      expected to be a list of filenames that need reading to fetch
      the raw content to analyze.

    - If `'file'`, the sequence items must have a 'read' method (file-like
      object) that is called to fetch the bytes in memory.

    - If `'content'`, the input is expected to be a sequence of items that
      can be of type string or byte.

encoding : str, default='utf-8'
    If bytes or files are given to analyze, this encoding is used to
    decode.

decode_error : {'strict', 'ignore', 'replace'}, default='strict'
    Instruction on what to do if a byte sequence is given to analyze that
    contains characters not of the given `encoding`. By default, it is
    'strict', meaning that a UnicodeDecodeError will be raised. Other
    values are 'ignore' and 'replace'.

strip_accents : {'ascii', 'unicode'} or callable, default=None
    Remove accents and perform other character normalization
    during the preprocessing step.
    'ascii' is a fast method that only works on characters that have
    a direct ASCII mapping.
    'unicode' is a slightly slower method that works on any characters.
    None (default) means no character normalization is performed.

    Both 'ascii' and 'unicode' use NFKD normalization from
    :func:`unicodedata.normalize`.

lowercase : bool, default=True
    Convert all characters to lowercase before tokenizing.

preprocessor : callable, default=None
    Override the preprocessing (string transformation) stage while
    preserving the tokenizing and n-grams generation steps.
    Only applies if ``analyzer`` is not callable.

tokenizer : callable, default=None
    Override the string tokenization step while preserving the
    preprocessing and n-grams generation steps.
    Only applies if ``analyzer == 'word'``.

analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
    Whether the feature should be made of word or character n-grams.
    Option 'char_wb' creates character n-grams only from text inside
    word boundaries; n-grams at the edges of words are padded with space.

    If a callable is passed it is used to extract the sequence of features
    out of the raw, unprocessed input.

    .. versionchanged:: 0.21
        Since v0.21, if ``input`` is ``'filename'`` or ``'file'``, the data
        is first read from the file and then passed to the given callable
        analyzer.

stop_words : {'english'}, list, default=None
    If a string, it is passed to _check_stop_list and the appropriate stop
    list is returned. 'english' is currently the only supported string
    value.
    There are several known issues with 'english' and you should
    consider an alternative (see :ref:`stop_words`).

    If a list, that list is assumed to contain stop words, all of which
    will be removed from the resulting tokens.
    Only applies if ``analyzer == 'word'``.

    If None, no stop words will be used. In this case, setting `max_df`
    to a higher value, such as in the range (0.7, 1.0), can automatically detect
    and filter stop words based on intra corpus document frequency of terms.

token_pattern : str, default=r"(?u)\\b\\w\\w+\\b"
    Regular expression denoting what constitutes a "token", only used
    if ``analyzer == 'word'``. The default regexp selects tokens of 2
    or more alphanumeric characters (punctuation is completely ignored
    and always treated as a token separator).

    If there is a capturing group in token_pattern then the
    captured group content, not the entire match, becomes the token.
    At most one capturing group is permitted.

ngram_range : tuple (min_n, max_n), default=(1, 1)
    The lower and upper boundary of the range of n-values for different
    n-grams to be extracted. All values of n such that min_n <= n <= max_n
    will be used. For example an ``ngram_range`` of ``(1, 1)`` means only
    unigrams, ``(1, 2)`` means unigrams and bigrams, and ``(2, 2)`` means
    only bigrams.
    Only applies if ``analyzer`` is not callable.

max_df : float or int, default=1.0
    When building the vocabulary ignore terms that have a document
    frequency strictly higher than the given threshold (corpus-specific
    stop words).
    If float in range [0.0, 1.0], the parameter represents a proportion of
    documents, integer absolute counts.
    This parameter is ignored if vocabulary is not None.

min_df : float or int, default=1
    When building the vocabulary ignore terms that have a document
    frequency strictly lower than the given threshold. This value is also
    called cut-off in the literature.
    If float in range of [0.0, 1.0], the parameter represents a proportion
    of documents, integer absolute counts.
    This parameter is ignored if vocabulary is not None.

max_features : int, default=None
    If not None, build a vocabulary that only consider the top
    `max_features` ordered by term frequency across the corpus.
    Otherwise, all features are used.

    This parameter is ignored if vocabulary is not None.

vocabulary : Mapping or iterable, default=None
    Either a Mapping (e.g., a dict) where keys are terms and values are
    indices in the feature matrix, or an iterable over terms. If not
    given, a vocabulary is determined from the input documents.

binary : bool, default=False
    If True, all non-zero term counts are set to 1. This does not mean
    outputs will have only 0/1 values, only that the tf term in tf-idf
    is binary. (Set `binary` to True, `use_idf` to False and
    `norm` to None to get 0/1 outputs).

dtype : dtype, default=float64
    Type of the matrix returned by fit_transform() or transform().

norm : {'l1', 'l2'} or None, default='l2'
    Each output row will have unit norm, either:

    - 'l2': Sum of squares of vector elements is 1. The cosine
      similarity between two vectors is their dot product when l2 norm has
      been applied.
    - 'l1': Sum of absolute values of vector elements is 1.
      See :func:`~sklearn.preprocessing.normalize`.
    - None: No normalization.

use_idf : bool, default=True
    Enable inverse-document-frequency reweighting. If False, idf(t) = 1.

smooth_idf : bool, default=True
    Smooth idf weights by adding one to document frequencies, as if an
    extra document was seen containing every term in the collection
    exactly once. Prevents zero divisions.

sublinear_tf : bool, default=False
    Apply sublinear tf scaling, i.e. replace tf with 1 + log(tf).

Attributes
----------
vocabulary_ : dict
    A mapping of terms to feature indices.

fixed_vocabulary_ : bool
    True if a fixed vocabulary of term to indices mapping
    is provided by the user.

idf_ : array of shape (n_features,)
    The inverse document frequency (IDF) vector; only defined
    if ``use_idf`` is True.

See Also
--------
CountVectorizer : Transforms text into a sparse matrix of n-gram counts.

TfidfTransformer : Performs the TF-IDF transformation from a provided
    matrix of counts.

Examples
--------
>>> from sklearn.feature_extraction.text import TfidfVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = TfidfVectorizer()
>>> X = vectorizer.fit_transform(corpus)
>>> vectorizer.get_feature_names_out()
array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], ...)
>>> print(X.shape)
(4, 9)